# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appl',
            name='deduct_fee_yes',
            field=models.BooleanField(default=False),
        ),
    ]
